name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 21.5.0
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm build

      - name: Package
        run: pnpm electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}